### ISSUE TITLE
SourceMap

### ISSUE THREAD

**Issue by osuketh** [LayerXcom/vyper-remix#11]
Is there any difference between solidity and vyper sourceMap?
If any difference, it'll affect warn and error message for vyper.

**Comment by osuketh** [comment]
also affect `remix-debug` and `remix-analyzer`.

**Comment by nrryuya** [comment]
https://github.com/ethereum/vyper/issues/878
https://github.com/ethereum/vyper/issues/642

**Comment by osuketh** [comment]
We can use this.
https://github.com/status-im/vyper-debug/blob/master/vdb/source_map.py

**Comment by osuketh** [comment]
sourceMappingDecoder
https://github.com/ethereum/remix/blob/master/remix-lib/src/sourceMappingDecoder.js

**Comment by nrryuya** [comment]
We might need source map to enable other remix features like debugging) in the future.
