### ISSUE TITLE
vyper code isn't updated Immediately

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/vyper-remix#38]

**Comment by yudetamago** [comment]
In this plugin's case, this implmentation tries to get updated state (means vyper code) just after `setState()`.
State will not be updated Immediately.

**Comment by yann300** [comment]
That one is a misbehavior in Remix.
created https://github.com/ethereum/remix-ide/issues/1614

**Comment by nrryuya** [comment]
Seems fixed.
