### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by osuketh** [LayerXcom/vyper-remix#5]
I don't like material ui, prefer semantic ui.
But same as remix style is the best.

**Comment by osuketh** [comment]
* get the css from remix-ide for button, text font, etc...
* use styled-components for css
* use semantic ui for complicated css like alert for getting file from remix

**Comment by nrryuya** [comment]
use Vyper logo!!!

**Comment by nrryuya** [comment]
v1
![image](https://user-images.githubusercontent.com/22876645/46323870-5a8ec700-c62b-11e8-9073-23e209b4cc7b.png)
